# Site settings
title: "R_B_prince"
email: chaihua483@126.com
description: "chaihua Blog"
baseurl: ""
url: ""
title_description: "r b prince"
title_image: "/img/avatar.jpg"
github_repository: https://github.com/chaihua483
addthis_id: ra-513c6fa83da6ec67
post_limit: 3

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# encoding
file_read_opts : {"encoding": "utf-8"}